export async function up(knex) {
  await knex.raw(`
    ALTER TABLE agents
    ADD COLUMN alternate_mobile_number VARCHAR(100) AFTER notes,
    ADD COLUMN whatsapp_number VARCHAR(100) AFTER alternate_mobile_number,
    ADD COLUMN current_house_no VARCHAR(100) AFTER whatsapp_number,
    ADD COLUMN current_street VARCHAR(150) AFTER current_house_no,
    ADD COLUMN current_area VARCHAR(150) AFTER current_street,
    ADD COLUMN current_landmark VARCHAR(150) AFTER current_area,
    ADD COLUMN current_city VARCHAR(100) AFTER current_landmark,
    ADD COLUMN current_district VARCHAR(100) AFTER current_city,
    ADD COLUMN current_state VARCHAR(100) AFTER current_district,
    ADD COLUMN current_country VARCHAR(100) AFTER current_state,
    ADD COLUMN current_pincode VARCHAR(20) AFTER current_country,
    ADD COLUMN same_as_current_address TINYINT(1) DEFAULT 0 AFTER current_pincode,
    ADD COLUMN permanent_house_no VARCHAR(100) AFTER same_as_current_address,
    ADD COLUMN permanent_street VARCHAR(150) AFTER permanent_house_no,
    ADD COLUMN permanent_area VARCHAR(150) AFTER permanent_street,
    ADD COLUMN permanent_landmark VARCHAR(150) AFTER permanent_area,
    ADD COLUMN permanent_city VARCHAR(100) AFTER permanent_landmark,
    ADD COLUMN permanent_district VARCHAR(100) AFTER permanent_city,
    ADD COLUMN permanent_state VARCHAR(100) AFTER permanent_district,
    ADD COLUMN permanent_country VARCHAR(100) AFTER permanent_state,
    ADD COLUMN permanent_pincode VARCHAR(20) AFTER permanent_country,
    ADD COLUMN facebook VARCHAR(255) AFTER permanent_pincode,
    ADD COLUMN instagram VARCHAR(255) AFTER facebook,
    ADD COLUMN linkedin VARCHAR(255) AFTER instagram,
    ADD COLUMN aadhaar_number VARCHAR(20) AFTER linkedin,
    ADD COLUMN pan_number VARCHAR(20) AFTER aadhaar_number,
    ADD COLUMN passport_number VARCHAR(50) AFTER pan_number,
    ADD COLUMN aadhaar_card VARCHAR(255) AFTER passport_number,
    ADD COLUMN pan_card VARCHAR(255) AFTER aadhaar_card,
    ADD COLUMN passport_file VARCHAR(255) AFTER pan_card,
    ADD COLUMN account_holder_name VARCHAR(255) AFTER passport_file,
    ADD COLUMN bank_name VARCHAR(255) AFTER account_holder_name,
    ADD COLUMN account_number VARCHAR(50) AFTER bank_name,
    ADD COLUMN ifsc_code VARCHAR(20) AFTER confirm_account_number,
    ADD COLUMN branch_name VARCHAR(255) AFTER ifsc_code,
    ADD COLUMN upi_id VARCHAR(255) AFTER branch_name;
 `);
}

export async function down(knex) {
  await knex.raw(`
    ALTER TABLE agents
        DROP COLUMN alternate_mobile_number,
        DROP COLUMN whatsapp_number,
        DROP COLUMN current_house_no,
        DROP COLUMN current_street,
        DROP COLUMN current_area,
        DROP COLUMN current_landmark,
        DROP COLUMN current_city,
        DROP COLUMN current_district,
        DROP COLUMN current_state,
        DROP COLUMN current_country,
        DROP COLUMN current_pincode,
        DROP COLUMN same_as_current_address,
        DROP COLUMN permanent_house_no,
        DROP COLUMN permanent_street,
        DROP COLUMN permanent_area,
        DROP COLUMN permanent_landmark,
        DROP COLUMN permanent_city,
        DROP COLUMN permanent_district,
        DROP COLUMN permanent_state,
        DROP COLUMN permanent_country,
        DROP COLUMN permanent_pincode,
        DROP COLUMN facebook,
        DROP COLUMN instagram,
        DROP COLUMN linkedin,
        DROP COLUMN aadhaar_number,
        DROP COLUMN pan_number,
        DROP COLUMN passport_number,
        DROP COLUMN aadhaar_card,
        DROP COLUMN pan_card,
        DROP COLUMN passport_file,
        DROP COLUMN account_holder_name,
        DROP COLUMN bank_name,
        DROP COLUMN account_number,
        DROP COLUMN ifsc_code,
        DROP COLUMN branch_name,
        DROP COLUMN upi_id;
    `);
}
